using System.Collections.Concurrent;

namespace GitLabSymbolServerProxy;

public class AuthorizationInfo {
	public const string GitLabPrivateTokenHeaderName = "PRIVATE-TOKEN";

	private AuthorizationInfo() { }

	public static AuthorizationInfo FromPersonalAccessToken(string personalAccessToken) {
		return new AuthorizationInfo {
			PersonalAccessToken = personalAccessToken
		};
	}

	// A fixed PAT, manually generated by someone and supplied to this proxy.
	public string PersonalAccessToken { get; init; } = string.Empty;

	// Applies authorization headers to a request.
	// If necessary, will call the supplied tokenGenerator function to get
	// OAuth access tokens.
	public AuthorizationInfo AuthorizeRequest(HttpRequestMessage request) {
		request.Headers.Add(GitLabPrivateTokenHeaderName, PersonalAccessToken);
		return this;
	}
}